urls = [

    {'Ladies Finger':'https://www.luluhypermarket.in/en-in/lady-s-finger-approx-500g/p/9136'},
    {'Tapioca':'https://www.luluhypermarket.in/en-in/tapioca-approx-1kg/p/7735_EA'},
    {'Ash Gourd':'https://www.luluhypermarket.in/en-in/ash-gourd-approx-500g/p/9112'},
    {'Snake Gourd':'https://www.luluhypermarket.in/en-in/fresh-snake-gourd-short-approx-500g/p/1113366'},
    {'Pumpkin':'https://www.luluhypermarket.in/en-in/pumpkin-approx-500g/p/10799_EA'},
    {'Bitter Gourd':'https://www.luluhypermarket.in/en-in/fresh-bitter-gourd-white-approx-500g/p/1113360'},
    {'Green Banana':'https://www.luluhypermarket.in/en-in/fresh-green-mountain-banana-approx-500g/p/1113359'},
    # {'Vellari':'https://www.luluhypermarket.in/en-in/fresh-vellari-approx-600g-700g/p/1113363'},
    # {'Curry Leaves':'https://www.luluhypermarket.in/en-in/curry-leaves-1pc/p/8342'},
    # {'Banana Nendran':'https://www.luluhypermarket.in/en-in/banana-nendran-approx-1kg/p/6287_EA'},
    # {'Birinjal Purple Stipe':'https://www.luluhypermarket.in/en-in/fresh-brinjal-purple-striped-approx-500g/p/1113361'},
    # {'Yam':'https://www.luluhypermarket.in/en-in/elephant-yam-approx-500g/p/7737_EA'},
    # {'Ginger':'https://www.luluhypermarket.in/en-in/fresh-ginger-approx-250g/p/1113346'},
    # {'Cucumber':'https://www.luluhypermarket.in/en-in/fresh-cucumber-kakdi-approx-600g/p/1113371'},
    # {'Bottle Gourd':'https://www.luluhypermarket.in/en-in/fresh-bottle-gourd-approx-500g/p/1113357'},
    # {'Tomato':'https://www.luluhypermarket.in/en-in/tomato-approx-550g-to-600g/p/7649_EA'},
    # {'Mint Leaves':'https://www.luluhypermarket.in/en-in/fresh-mint-leaves-1pc/p/1134464'},
    # {'Alphonso Mango':'https://www.luluhypermarket.in/en-in/mango-alphonso/p/6331'},
    # {'Ridge Gourd':'https://www.luluhypermarket.in/en-in/fresh-ridge-gourd-approx-600g-700g/p/1113362'},
    # {'Green Valli Payar':'https://www.luluhypermarket.in/en-in/string-beans-approx-500g/p/665488_EA'},
    # {'Green Chilli':'https://www.luluhypermarket.in/en-in/chilli-green-approx-250g/p/7582'},
    # {'Coriander Leaves':'https://www.luluhypermarket.in/en-in/coriander-leaves-1-bunch/p/8341'},
    # {'Carrot':'https://www.luluhypermarket.in/en-in/fresh-carrot-approx-500g/p/1113343'},
    # {'Cabbage':'https://www.luluhypermarket.in/en-in/cabbage-approx-500g/p/8253_EA'},
    # {'Potato':'https://www.luluhypermarket.in/en-in/fresh-potato-premium-approx-1kg/p/1113344'},
    # {'Garlic':'https://www.luluhypermarket.in/en-in/garlic-500g/p/7603'},
    # {'Celery':'https://www.luluhypermarket.in/en-in/celery-approx-250g/p/8286'},
    # {'Cauliflower':'https://www.luluhypermarket.in/en-in/fresh-cauliflower-approx-700g-800g/p/1113354'},
    # {'Beetroot':'https://www.luluhypermarket.in/en-in/fresh-beetroot-approx-500g/p/1113350'},
    # {'Broccoli':'https://www.luluhypermarket.in/en-in/broccoli-approx-500g/p/8282'},
    # {'Chayote':'https://www.luluhypermarket.in/en-in/fresh-chow-chow-approx-500g/p/1113367'},
    # {'Cabbage':'https://www.luluhypermarket.in/en-in/cabbage-approx-500g/p/8253_EA'},
    # {'Capsicum-Green':'https://www.luluhypermarket.in/en-in/fresh-capsicum-green-approx-500g/p/1113349'},
    # {'Small Onion':'https://www.luluhypermarket.in/en-in/small-onion-500gm/p/10808'},
    # {'Big Onion':'https://www.luluhypermarket.in/en-in/fresh-onion-red-approx-1kg/p/1113342'},
    # {'Lemon':'https://www.luluhypermarket.in/en-in/fresh-lime-approx-250g/p/1113369'},
    # {'Orange':'https://www.luluhypermarket.in/en-in/orange-valencia-approx-1kg/p/10708_EA'},
    # {'Gooseberry':'https://www.luluhypermarket.in/en-in/fresh-gooseberry-approx-500g/p/1113352'},
    # {'Haricot Beans':'https://www.luluhypermarket.in/en-in/haricot-beans-500gm/p/658748'},
    # {'Pomgranate':'https://www.luluhypermarket.in/en-in/pomegranate-red-approx-1-1kg-to-1-2kg/p/10632_EA'},
    # {'Sweetcorn':'https://www.luluhypermarket.in/en-in/sweet-corn-pack-of-2/p/155186'},
    # {'Lettuce':'https://www.luluhypermarket.in/en-in/fresh-lettuce-iceberg-approx-250g/p/1113347'},
    # {'Baby Corn':'https://www.luluhypermarket.in/en-in/baby-corn-peeled-1-packet/p/10593'},
    # {'Cabsicum Yellow':'https://www.luluhypermarket.com/en-ae/capsicum-yellow-500g-approx-weight/p/18799_EA'},
    # {'Yellow Zuchini':'https://www.luluhypermarket.in/en-in/zucchini-yellow/p/8331'},
    # {'Capsicum-Red':'https://www.luluhypermarket.in/en-in/fresh-capsicum-red-approx-500g/p/1113353'},
    # {'Raw Mango':'https://www.luluhypermarket.in/en-in/fresh-green-mango-approx-1kg/p/1113356'},
    # {'Letuce Romaine':'https://www.luluhypermarket.in/en-in/lettuce-romaine-approx-250g/p/8295'},
    # {'Banana Stem':'https://www.luluhypermarket.com/en-kw/banana-pindi-stem-500g-approx-weight/p/481354_EA'},
    # {'Cocunut':'https://www.luluhypermarket.in/en-in/coconut-1pc/p/1076962'},
    # {'Pineapple':'https://www.luluhypermarket.in/en-in/pineapple-approx-1-3kg-to-1-5-kg/p/11071_EA'},
    # {'Drumstick':'https://www.luluhypermarket.in/en-in/drumstick-250gm/p/9134_EA'},
    # {'Radish White':'https://www.luluhypermarket.in/en-in/fresh-radish-white-approx-500g/p/1113372'},
    # {'Papaya':'https://www.luluhypermarket.com/en-ae/papaya-fruit-india-1kg-approx-weight/p/18671_EA'},
    # {'Mango Banganapalli':'https://www.luluhypermarket.in/en-in/mango-banganapalli-approx-1kg/p/6334'},
    # {'Seedless Green Grapes':'https://www.luluhypermarket.in/en-in/grapes-black-seedless-premium-approx-500g/p/1105638'},

    #bigbasket

    {'Ladies Finger':'https://www.bigbasket.com/pd/10000144/fresho-ladies-finger-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    {'Ash Gourd': 'https://www.bigbasket.com/pd/10000011/fresho-ash-gourd-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    {'Tapioca':'https://www.bigbasket.com/pd/10000197/fresho-tapioca-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    {'Amaranthus-Green':'https://www.bigbasket.com/pd/10000001/fresho-amaranthus-green-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    {'Pumpkin':'https://www.bigbasket.com/pd/40023471/fresho-pumpkin-organically-grown-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    {'Bitter Gourd':'https://www.bigbasket.com/pd/10000049/fresho-bitter-gourd-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    {'Banana Raw':'https://www.bigbasket.com/pd/10000168/fresho-banana-raw-green-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Vellari':'https://www.bigbasket.com/pd/40023195/fresho-cucumber-malabar-organically-grown-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Curry Leaves':'https://www.klfresh.com/products/product-detail/curry-leaves-karivepalla/1166'},
    # {'Papaya Raw':'https://www.bigbasket.com/pd/10000380/fresho-papaya-raw-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Pomelo':'https://www.bigbasket.com/pd/40083559/fresho-pomelo-peeled-200-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Banana Nendran':'https://www.bigbasket.com/pd/10000346/fresho-banana-nendran-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Birinjal Purple Stipe':'https://www.bigbasket.com/pd/10000060/fresho-brinjal-varikatri-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Yam':'https://www.bigbasket.com/pd/40201308/fresho-yam-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Ginger':'https://www.bigbasket.com/pd/10000118/fresho-ginger-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Cucuumber':'https://www.bigbasket.com/pd/10000103/fresho-cucumber-500-g/'},
    # {'Bottle gourd':'https://www.bigbasket.com/pd/20000745/fresho-bottle-gourd-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Colocasia':'https://www.bigbasket.com/pd/40049431/fresho-colocasia-organically-grown-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Tomato':'https://www.bigbasket.com/pd/40022638/fresho-tomato-local-organically-grown-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Ivy Gourd':'https://www.bigbasket.com/pd/10000091/fresho-coccinia-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Mint Leaves':'https://www.bigbasket.com/pd/10000137/fresho-mint-leaves-100-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Ridge Gourd':'https://www.bigbasket.com/pd/10000176/fresho-ridge-gourd-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Green Valli Payar':'https://www.bigbasket.com/pd/10000275/fresho-beans-cowpea-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Green Chilli':'https://www.bigbasket.com/pd/10000082/fresho-chilli-green-long-medium-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Coriander Leaves':'https://www.bigbasket.com/pd/10000097/fresho-coriander-leaves-100-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Carrot':'https://www.bigbasket.com/pd/10000072/fresho-carrot-orange-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Cabbage':'https://www.bigbasket.com/pd/10000066/fresho-cabbage-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Potato':'https://www.bigbasket.com/pd/10000159/fresho-potato-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Garlic':'https://www.bigbasket.com/pd/10000115/fresho-garlic-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Poovan Pazham':'https://www.bigbasket.com/pd/60000054/fresho-banana-poovan-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Celery Leaves':'https://www.bigbasket.com/pd/10000075/fresho-celery-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Broad Beans':'https://www.bigbasket.com/pd/10000038/fresho-beans-broad-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Cauli Flower':'https://www.bigbasket.com/pd/10000074/fresho-cauliflower-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Beetroot':'https://www.bigbasket.com/pd/10000046/fresho-beetroot-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Broccoli':'https://www.bigbasket.com/pd/10000063/fresho-broccoli-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Chow Chow ':'https://www.bigbasket.com/pd/10000087/fresho-chow-chow-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Chinese Cabbage':'https://www.bigbasket.com/pd/10000084/fresho-chinese-cabbage-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Capsicum-Green':'https://www.bigbasket.com/pd/10000069/fresho-capsicum-green-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Spring Onion':'https://www.bigbasket.com/pd/20000981/fresho-spring-onion-100-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Small Onion':'https://www.bigbasket.com/pd/10000178/fresho-sambhar-onion-small-onion-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Big Onion':'https://www.bigbasket.com/pd/10000148/fresho-onion-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Baby Potato':'https://www.bigbasket.com/pd/10000024/fresho-baby-potato-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Lemon':'https://www.bigbasket.com/pd/10000127/fresho-lemon-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Orange':'https://www.bigbasket.com/pd/20000910/fresho-orange-imported-6-pcs/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Mosambi':'https://www.bigbasket.com/pd/40203347/fresho-mosambi-economy-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Gooseberry':'https://www.bigbasket.com/pd/10000293/fresho-amla-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Guava':'https://www.bigbasket.com/pd/10000370/fresho-guava-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Robust Banana':'https://www.bigbasket.com/pd/40179390/fresho-baby-banana-robusta-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Beans-Haricot':'https://www.bigbasket.com/pd/40089743/fresho-beans-haricot-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Pomgranate':'https://www.bigbasket.com/pd/10000269/fresho-pomegranate-4-pcs/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Khol Khol':'https://www.bigbasket.com/pd/10000278/fresho-knol-khol-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Sweet Corn':'https://www.bigbasket.com/pd/40004992/fresho-sweet-corn-2-pcs/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Lettuce':'https://www.bigbasket.com/pd/10000133/fresho-lettuce-iceberg-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Red Cabbage':'https://www.bigbasket.com/pd/10000171/fresho-cabbage-red-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Zucchini-Green':'https://www.bigbasket.com/pd/10000123/fresho-zucchini-green-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Cabsicum Yellow':'https://www.bigbasket.com/pd/10000323/fresho-capsicum-yellow-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Zucchini Yellow':'https://www.bigbasket.com/pd/10000211/fresho-zucchini-yellow-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Leeks':'https://www.bigbasket.com/pd/10000597/fresho-leeks-100-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Capsicum Red':'https://www.bigbasket.com/pd/40149660/fresho-capsicum-red-2-pcs/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Tender Coconut':'https://www.bigbasket.com/pd/40057966/fresho-tender-coconut-medium-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Potato Ooty':'https://www.bigbasket.com/pd/40021628/fresho-ooty-potato-medium-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Cherry Tomato':'https://www.bigbasket.com/pd/10000198/fresho-tomato-cherry-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Raw Mango':'https://www.bigbasket.com/pd/10000590/fresho-totapuri-mango-1-kg/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Lettuce Red':'https://www.klfresh.com/products/product-detail/lettuce-red/1395'},
    # {'Lettuce Romaine':'https://www.bigbasket.com/pd/40016096/fresho-lettuce-romaine-100-to-150-gm/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Banana Stem':'https://www.bigbasket.com/pd/40036724/fresho-banana-stem-organically-grown-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Coconut':'https://www.bigbasket.com/pd/10000093/fresho-coconut-medium-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Pineapple':'https://www.bigbasket.com/pd/10000156/fresho-pineapple-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Drumstick':'https://www.bigbasket.com/pd/10000109/fresho-drumstickmoringa-250-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Radish White':'https://www.bigbasket.com/pd/10000166/fresho-radish-white-500-g/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Musk Melon':'https://www.bigbasket.com/pd/50000534/fresho-muskmelon-organically-grown-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},
    # {'Papaya': 'https://www.bigbasket.com/pd/40022647/fresho-papaya-organically-grown-1-pc/?nc=cl-prod-list&t_pg=&t_p=&t_s=cl-prod-list&t_pos=1&t_ch=desktop'},

    #jiomart

    {'Ladies Finger':'https://www.jiomart.com/p/groceries/bhendi-okra-per-kg/590003550'},
    {'Tapioca':'https://www.jiomart.com/p/groceries/tapioca-per-kg/590033816'},
    {'Ash Gourd':'https://www.jiomart.com/p/groceries/ash-gourd-slice-500-g/590000224'},
    {'Snake Gaurd':'https://www.jiomart.com/p/groceries/snake-gourd-hybrid-small-1-kg/590000180'},
    {'Pumpkin':'https://www.jiomart.com/p/groceries/pumpkin-slice-1-kg/590000223'},
    # {'Bitter Gourd':'https://www.jiomart.com/p/groceries/country-bitter-gourd-per-kg/590000497'},
    # {'Banana Raw':'https://www.jiomart.com/p/groceries/banana-raw-1-kg/590000502'},
    # {'Vellari':'https://www.jiomart.com/p/groceries/cucumber-madras-1-kg/590000171'},
    # {'Banana Nendran':'https://www.jiomart.com/p/groceries/banana-nendran-1-kg/590000614'},
    # {'Birinjal Purple Stipe':'https://www.jiomart.com/p/groceries/brinjal-purple-striped-1-kg/590000165'},
    # {'Yam':'https://www.jiomart.com/p/groceries/local-yam-slice-500-g/590001616'},
    # {'Ginger':'https://www.jiomart.com/p/groceries/ginger-indian-200-g/590003531'},
    # {'Cucumber':'https://www.jiomart.com/p/groceries/spring-onion-per-bunch/590003548'},
    # {'Bottle gourd':'https://www.jiomart.com/p/groceries/lauki-bottle-gourd-1-kg/590000174'},
    # {'Colocasia':'https://www.jiomart.com/p/groceries/colocasia-small-1-kg/590000137'},
    # {'Tomato':'https://www.jiomart.com/p/groceries/amaranthus-1-bunch/590003517'},
    # {'Ivy Gourd':'https://www.jiomart.com/p/groceries/coccinia-500-g/590000175'},
    # {'Green Valli Payar':'https://www.jiomart.com/p/groceries/cowpea-kuttipayar-per-kg/590001310'},
    # {'Green Chilli':'https://www.jiomart.com/p/groceries/chilli-green-200-gram/590003533'},
    # {'Carrot':'https://www.jiomart.com/p/groceries/carrot-regular-1-kg/590000186'},
    # {'Cabbage':'https://www.jiomart.com/p/groceries/cabbage-1-pc/590002370'},
    # {'French Beans':'https://www.jiomart.com/p/groceries/french-beans-500g/590000157'},
    # {'Potato':'https://www.jiomart.com/p/groceries/tapioca-1-kg/590003516'},
    # {'Garlic':'https://www.jiomart.com/p/groceries/garlic-indian-200-g/590003532'},
    # {'Poovan Pazham':'https://www.jiomart.com/p/groceries/banana-robusta-6-pcs-box/590001285'},
    # {'Broad Beans':'https://www.jiomart.com/p/groceries/cluster-beans-1-kg/590000155'},
    # {'Cauli Flower':'https://www.jiomart.com/p/groceries/cauliflower-1-pc/590000619'},
    # {'Beetroot':'https://www.jiomart.com/p/groceries/alfalfa-sprouts-1-pack/590003540'},
    # {'Chow Chow':'https://www.jiomart.com/p/groceries/chow-chow-bangalore-brinjal-500-g/590000169'},
    # {'Capsicum Green':'https://www.jiomart.com/p/groceries/green-capsicum-500-g/590003662'},
    # {'Small Onion':'https://www.jiomart.com/p/groceries/onion-sambhar-1-kg/590004163'},
    # {'Big Onion':'https://www.jiomart.com/p/groceries/lentil-sprouts-200-g/590003515'},
    # {'Baby Potato':'https://www.jiomart.com/p/groceries/potato-baby-500-g/590000094'},
    # {'Lemon':'https://www.jiomart.com/p/groceries/lemon-100-g/590004153'},
    # {'Orange':'https://www.jiomart.com/p/groceries/orange-imported-1-kg/590000025'},
    # {'Mossambi':'https://www.jiomart.com/p/groceries/mosambi-1-kg/590001673'},
    # {'Gooseberry':'https://www.jiomart.com/p/groceries/amla-indian-gooseberry-500-g/590000126'},
    # {'Beans Haricott':'https://www.jiomart.com/p/groceries/beans-string-less-500-g/590000160'},
    # {'Pomgranate':'https://www.jiomart.com/p/groceries/pomegranate-kesar-1-kg/590000082'},
    # {'Cabsicum Yellow':'https://www.jiomart.com/p/groceries/yellow-capsicum-200-g/590000145'},
    # {'Capsicum Red':'https://www.jiomart.com/p/groceries/red-capsicum-200-g/590000144'},
    # {'Raw Mango':'https://www.jiomart.com/p/groceries/mango-totapuri-1-kg/590000047'},
    # {'Coconut':'https://www.jiomart.com/p/groceries/coconut-1-pc/590000086'},
    # {'Pineapple':'https://www.jiomart.com/p/groceries/pineapple-queen-1-kg/590000663'},
    # {'Drumstick':'https://www.jiomart.com/p/groceries/drumstick-each/590000128'},
    # {'Musk Melon':'https://www.jiomart.com/p/groceries/musk-melon-1-kg/590000051'},
    # {'Papaya':'https://www.jiomart.com/p/groceries/papaya-normal-1-5-kg/590000069'},



    #klfresh

    {'Ladies Finger':'https://www.klfresh.com/products/product-detail/ladies-finger/1153'},
    {'Tapioca':'https://www.klfresh.com/products/product-detail/tapiocakolli/1147'},
    {'Ash Gourd':'https://www.klfresh.com/products/product-detail/ash-gourd-kumbalanga/1149'},
    {'Snake Gaurd':'https://www.klfresh.com/products/product-detail/snake-gourd-padavalam/1144'},
    # {'Pumpkin':'https://www.klfresh.com/products/product-detail/pumpkin-yellow/1150'},
    # {'Bitter Gourd':'https://www.klfresh.com/products/product-detail/bitter-gourdkaipakka-pavakka/1102'},
    # {'Banana Raw':'https://www.klfresh.com/products/product-detail/banana-greenvazhakakaya/1170'},
    # {'Curry Leaves':'https://www.klfresh.com/products/product-detail/curry-leaves-karivepalla/1166'},
    # {'Papaya Raw':'https://www.klfresh.com/products/product-detail/papaya-green/1123'},
    # {'Banana Nendran':'https://www.klfresh.com/products/product-detail/banana-nendran/1043'},
    # {'Birinjal Stripe':'https://www.klfresh.com/products/product-detail/eggplant-purplebrinjal/1117'},
    # {'Kandari Mulaku':'https://www.klfresh.com/products/product-detail/chillies-kandhari/1126'},
    # {'Yam':'https://www.klfresh.com/products/product-detail/yam-elephant-foot-chena/1111'},
    # {'Ginger':'https://www.klfresh.com/products/product-detail/gingerinji/1103'},
    # {'Cucumber':'https://www.klfresh.com/products/product-detail/cucumber-local/1157'},
    # {'Bottle Gourd':'https://www.klfresh.com/products/product-detail/bottle-gourd-churakka/1104'},
    # {'Tomato':'https://www.klfresh.com/products/product-detail/tomato/1154'},
    # {'Ivy Gourd':'https://www.klfresh.com/products/product-detail/kovakkaivy-gourdcoccinea/1156'},
    # {'Mint Leaves': 'https://www.klfresh.com/products/product-detail/mintputhina/1165'},
    # {'Ridge Gourd':'https://www.klfresh.com/products/product-detail/ridge-gourdpeechinga/1130'},
    # {'Green Valli Payar':'https://www.klfresh.com/products/product-detail/beans-payar-long/1136'},
    # {'Green Chilli':'https://www.klfresh.com/products/product-detail/chillies-greenmelagu/1121'},
    # {'Coriander Leaves':'https://www.klfresh.com/products/product-detail/coriandermalli-leaves/1164'},
    # {'Carrot':'https://www.klfresh.com/products/product-detail/carrots/1108'},
    # {'Cabbage':'https://www.klfresh.com/products/product-detail/cabbage/1107'},
    # {'French Beans':'https://www.klfresh.com/products/product-detail/beans-cluster-kothamara/1196'},
    # {'Potato':'https://www.klfresh.com/products/product-detail/potato-big/1139'},
    # {'Garlic':'https://www.klfresh.com/products/product-detail/garlic-premium-quality/1118'},
    # {'Poovan Pazham':'https://www.klfresh.com/products/product-detail/banana-cheru-pazham/1046'},
    # {'Celery Leaves':'https://www.klfresh.com/products/product-detail/celery/1110'},
    # {'Rose Mary Leaves':'https://www.klfresh.com/products/product-detail/rosemary-leaves/1391'},
    # {'Broad Beans':'https://www.klfresh.com/products/product-detail/beans-cluster-kothamara/1196'},
    # {'Cauli Flower':'https://www.klfresh.com/products/product-detail/cauliflower/1109'},
    # {'Beetroot':'https://www.klfresh.com/products/product-detail/beetroot/1101'},
    # {'Broccoli':'https://www.klfresh.com/products/product-detail/broccoli/1182'},
    # {'Chow Chow':'https://www.klfresh.com/products/product-detail/chow-chow/1161'},
    # {'Chinese Cabbage':'https://www.klfresh.com/products/product-detail/chinese-cabbage/1392'},
    # {'Capsicum-Green':'https://www.klfresh.com/products/product-detail/capsicum-green/1124'},
    # {'Strawberry':'https://www.klfresh.com/products/product-detail/strawberry/1038'},
    # {'Spring Onion':'https://www.klfresh.com/products/product-detail/spring-onion/1145'},
    # {'Small Onion':'https://www.klfresh.com/products/product-detail/onion-smallcheriya-ullishallots/1143'},
    # {'Big Onion':'https://www.klfresh.com/products/product-detail/onionulli/1135'},
    # {'Baby Potato':'https://www.klfresh.com/products/product-detail/potato-smallurulakizhangu/1151'},
    # {'Lemon':'https://www.klfresh.com/products/product-detail/lemon/1127'},
    # {'Orange':'https://www.klfresh.com/products/product-detail/orange/1027'},
    # {'Mossambi':'https://www.klfresh.com/products/product-detail/orange-mosambi/1045'},
    # {'Gooseberry':'https://www.klfresh.com/products/product-detail/amla-nellika/1155'},
    # {'Guava':'https://www.klfresh.com/products/product-detail/guava/1013'},
    # {'Roburst banana':'https://www.klfresh.com/products/product-detail/banana-robust-banana/1048'},
    # {'Brans haricot':'https://www.klfresh.com/products/product-detail/beans/1105'},
    # {'Pomgranate':'https://www.klfresh.com/products/product-detail/pomegranate-fresh-premium-quality/1032'},
    # {'Sweet corn':'https://www.klfresh.com/products/product-detail/corncholam/1114'},
    # {'Lettuce Ice Berg':'https://www.klfresh.com/products/product-detail/lettuce/1129'},
    # {'Red Cabbage':'https://www.klfresh.com/products/product-detail/purple-cabbage/1285'},
    # {'Zucchini Green':'https://www.klfresh.com/products/product-detail/zucchini-green/1183'},
    # {'Cabsicum Yellow':'https://www.klfresh.com/products/product-detail/capsicum-yellow/1159'},
    # {'Leeks':'https://www.klfresh.com/products/product-detail/leeks/1398'},
    # {'Capsicum Red':'https://www.klfresh.com/products/product-detail/capsicum-red/1142'},
    # {'Tender Coconut':'https://www.klfresh.com/products/product-detail/tender-coconut/1010'},
    # {'Cherry Tomato':'https://www.klfresh.com/products/product-detail/cherry-tomato/1284'},
    # {'Lettuce Red':'https://www.klfresh.com/products/product-detail/lettuce-red/1395'},
    # {'Lettuce Romaine':'https://www.klfresh.com/products/product-detail/lettuce-romaine/1394'},
    # {'Banana Stem':'https://www.klfresh.com/products/product-detail/banana-stem-organically-grown/1163'},
    # {'Coconut':'https://www.klfresh.com/products/product-detail/coconut-medium-1-pc-approx-300-g-to-400-g/1179'},
    # {'Pineapple':'https://www.klfresh.com/products/product-detail/pineapple/1033'},
    # {'Drumstick':'https://www.klfresh.com/products/product-detail/drumstick-muringakol/1131'},
    # {'Papaya':'https://www.klfresh.com/products/product-detail/papaya/1028'},

    #findfresh
    {'Ladies Finger':'https://www.findfresh.in/Vendakka_Ladies_finger_g_65'},
    {'Tapioca':'https://www.findfresh.in/Tapioca_%E0%B4%95%E0%B4%AA%E0%B4%AA_Kappa_kg_11'},
    {'Pumpkin':'https://www.findfresh.in/%E0%B4%AE%E0%B4%A4%E0%B4%A4%E0%B4%99%E0%B4%99_Pumpkin_mathanga_kg_16'},
    {'Bitter Gourd':'https://www.findfresh.in/Pavakka_Bitter_gourd_g_30'},
    {'Banana Raw':'https://www.findfresh.in/Raw_Banana_Kg_33'},

    # {'Vellari':'https://www.findfresh.in/Cucumber_Sambar_Vellari_kg_71'},
    # {'Curyy Leaves':'https://www.findfresh.in/Curry_leaves_%E0%B4%95%E0%B4%B1%E0%B4%B5%E0%B4%AA%E0%B4%AA%E0%B4%B2_g_15'},
    # {'Banana Nendran':'https://www.findfresh.in/Banana_%E0%B4%A8%E0%B4%A8%E0%B4%A4%E0%B4%B0%E0%B4%AA%E0%B4%AA%E0%B4%B4_kg_35'},
    # {'Yam':'https://www.findfresh.in/Chena_elephant_yam_Kg_34'},
    # {'Ginger':'https://www.findfresh.in/Ginger_%E0%B4%87%E0%B4%9E%E0%B4%9A_g_97'},
    # {'Cucumber':'https://www.findfresh.in/Cucumber_Salad_kg_38'},
    # {'Colocasia':'https://www.findfresh.in/%E0%B4%9A%E0%B4%AE%E0%B4%AA_chemb_colocasia_g_137'},
    # {'Tomato':'https://www.findfresh.in/Tomato_84'},
    # {'Ivy Gourd':'https://www.findfresh.in/kovakka_ivy_gourd_g_54'},
    # {'Mint Leaves':'https://www.findfresh.in/Pudina_leaves_mint_leaves_%E0%B4%AA%E0%B4%A4%E0%B4%A8_%E0%B4%87%E0%B4%B2_g_158'},
    # {'Green Chilli':'https://www.findfresh.in/Green_chilli_%E0%B4%AA%E0%B4%9A%E0%B4%9A_%E0%B4%AE%E0%B4%B3%E0%B4%95_g_94'},
    # {'Coriander Leaves':'https://www.findfresh.in/Coriander_Leaves_g_92'},
    # {'Carrot':'https://www.findfresh.in/Carrot_%E0%B4%95%E0%B4%AF%E0%B4%B0%E0%B4%B1%E0%B4%B1_g_88'},
    # {'Cabbage':'https://www.findfresh.in/Cabbage_%E0%B4%95%E0%B4%AC%E0%B4%9C_pc_Approx_g_to_g_87'},
    # {'Potato':'https://www.findfresh.in/Potato_%E0%B4%89%E0%B4%B0%E0%B4%B3_%E0%B4%95%E0%B4%B4%E0%B4%99%E0%B4%99_g_86'},
    # {'Garlic':'https://www.findfresh.in/Garlic_%E0%B4%B5%E0%B4%B3%E0%B4%A4%E0%B4%A4%E0%B4%B3%E0%B4%B3_g_93'},
    # {'Poovan Pazham':'https://www.findfresh.in/Banana_njalipoovan_kg_36'},
    # {'Broad Beans':'https://www.findfresh.in/Beans_%E0%B4%AC%E0%B4%B8_g_95'},
    # {'Cauli Flower':'https://www.findfresh.in/Cauliflower_%E0%B4%95%E0%B4%B3_%E0%B4%AB%E0%B4%B3%E0%B4%B5_pc_approx_to_g_91'},
    # {'Beetroot':'https://www.findfresh.in/Beetroot_%E0%B4%AC%E0%B4%B1%E0%B4%B1%E0%B4%B1%E0%B4%9F%E0%B4%9F_g_89'},
    # {'Capsicum-Green':'https://www.findfresh.in/Capsicum_Green_g_124'},
    # {'Small Onion':'https://www.findfresh.in/Small_Onion_%E0%B4%89%E0%B4%B3%E0%B4%B3_g_96'},
    # {'Big Onion':'https://www.findfresh.in/Big_Onion_savala_%E0%B4%B8%E0%B4%B5%E0%B4%B3_g_85'},
    # {'Lemon':'https://www.findfresh.in/Lemon_%E0%B4%9A%E0%B4%B1%E0%B4%A8%E0%B4%B0%E0%B4%99%E0%B4%99_g_117'},
    # {'Orange':'https://www.findfresh.in/Orange_%E0%B4%93%E0%B4%B1%E0%B4%9E%E0%B4%9A_g_142'},
    # {'Mosambi':'https://www.findfresh.in/Orange_%E0%B4%93%E0%B4%B1%E0%B4%9E%E0%B4%9A_g_142'},
    # {'Gooseberry':'https://www.findfresh.in/Nellikka_%E0%B4%A8%E0%B4%B2%E0%B4%B2%E0%B4%95%E0%B4%95_Gooseberry_g_123'},
    # {'Pomgranate':'https://www.findfresh.in/%E0%B4%AE%E0%B4%A4%E0%B4%B3_%E0%B4%A8%E0%B4%B0%E0%B4%99%E0%B4%99_Pomegranate_g_143'},
    # {'Coconut':'https://www.findfresh.in/Coconut_%E0%B4%A4%E0%B4%99%E0%B4%99_pc_9'},
    # {'Pineapple':'https://www.findfresh.in/%E0%B4%95%E0%B4%A4%E0%B4%9A%E0%B4%9A%E0%B4%95%E0%B4%95_Pineapple_kg_21'},
    # {'Papaya':'https://www.findfresh.in/%E0%B4%AA%E0%B4%AA%E0%B4%AA%E0%B4%AF_%E0%B4%AA%E0%B4%B4_papaya_fruit_kg_20'},

]

